### ISSUE TITLE
请问 IoT Link 什么时候考虑支持 Mac？

### ISSUE THREAD

**Issue by ghost** [LiteOS/LiteOS_Lab#389]
Mac 下开发单片机太痛苦了，没有一个合适的平台。
请问有支持计划吗？

**Comment by cruise2018** [comment]
1, hi ,你可以在MAC下使用SW4ST这个工具开发MCU的程序，这个是一个基于ECLIPSE的工具，是跨平台的，可以参考https://github.com/LiteOS/LiteOS_Lab/blob/iot_link/doc/Huawei_IoT_Link_SDK_IDE_SW4STM32(AC6)_Guide.md,这个工具有MACOS版本的
2，如果你想使用MAC来体验这个程序，可以参考：可以参考https://github.com/LiteOS/LiteOS_Lab/blob/iot_link/tools/kconfig/Readme.md
