### ISSUE TITLE
Problem with OeanConnect (EVB_M1)

### ISSUE THREAD

**Issue by fabriformo** [LiteOS/LiteOS_Lab#63]
Hi, I created a project with the EVB_M1 board following the guide "A Step-by-Step Guide To Create Your First NB-IoT Application". When I try to connect the board to OceanConnect (https://testsp.hw-oc.com) the status of the device always remains Offline and I cannot connect to the platform.

In the application I set the server with the address indicated in "Device Access Address" both with port 5683 and 5684. I also tried with QCOM via AT commands but it does not connect the same.

What can the error be?

Thank you

**Comment by cruise2018** [comment]
Hi
1, first you should check if any NB net could be find around you. You could use the NB MODULE only ,and try the at command(AT+CSQ , if 99 it means no valid signal there)
2, The project supposed you use the 1nce NB SIM CARD, if not ,check the apn and plmn with the Telecom Operater

**Comment by fabriformo** [comment]
> Hi
> 1, first you should check if any NB net could be find around you. You could use the NB MODULE only ,and try the at command(AT+CSQ , if 99 it means no valid signal there)
> 2, The project supposed you use the 1nce NB SIM CARD, if not ,check the apn and plmn with the Telecom Operater

Yes, I've already done these things. I tried to send the data to a private OceanConnect platform and the light sensor data is sent. I can't send it to the http: //testsp.hw-oc.com platform (after creating my account). What procedure should I follow and what server address should I enter?

**Comment by cruise2018** [comment]
1，	Sorry I don’t know whether you  have get any signal yet(USE AT+CSQ)
2，	And the source code interface support the domain name, like : config.server = "testsp.hw-oc.com,5683"(you could find it in the main.c file)
3，	And the code you download now only support the un_encrypment mode,so the default port is 5683

Good Luck!
