### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by MarcoVigo** [LiteOS/LiteOS_Lab#65]
There is a way to use the gps module in EVB_M1 ?
I've used the guide of the light sensor project and that worked, I was wondering if there was a way to do the same thing with the GPS sensor.

**Comment by cruise2018** [comment]
yes, you could do it, and the EVB_M1 has the port for the GPS mini board. We have add the code  to the project, but we have not test it yet. you could test with the datasheet of the GPS sensor.
