### ISSUE TITLE
How to import ST libraries

### ISSUE THREAD

**Issue by MarcoVigo** [LiteOS/LiteOS_Lab#98]
There is a way to import en.x-cube-cryptolib libraries?
In Project-Properties-C/C++ Build-Settings don't appear the tab -Tool Setting 
through which it is possible to import libraries  in other system workbench's projects.
Normally this tab appears when we generate automatically makefile, but in the guide for this project we deselect the option and import the makefile from targets/IoTClub-EVB-M1/GCC .

There is another way to fix this or another way to use ST crypto libraries inside the project?

**Comment by cruise2018** [comment]
HI, you could use the eclipse or other tools like this to solve the tab problem. And you could refer to the ST crypto as the 3rd library in the link process when compile the project.
